name: Run SiEPIC-Tool Layout tests 

on:
  workflow_dispatch:
  push:
    paths:
      - '**'
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - master


jobs:
  test_layouts:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

        # can also specify python version if needed
      - name: setup python
        uses: actions/setup-python@v4

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install klayout numpy scipy pytest

      - name: Test with pytest
        run: pytest klayout_dot_config/tech
  